"""Static contract tests for the OpenClaw adapter (openclaw-plugin/).

Self-contained unittest using only the Python standard library. No
Node.js, npm, or OpenClaw CLI installation is required.

These tests validate the static file/manifest contracts that OpenClaw
reads *before* loading plugin runtime code:

  - openclaw.plugin.json exists, is valid JSON, and has the required
    fields (id, configSchema, contracts.tools, activation).
  - contracts.tools matches the tool names declared in src/index.ts.
  - package.json has openclaw extensions metadata and typebox dep.
  - src/index.ts uses defineToolPlugin and declares the expected tools.
  - README documents install and validation commands.
  - All files follow the Adjacent writing conventions (no em-dash, no
    emoji, mid-quote convention present, % not pp).

Run: python3 -m unittest tests.openclaw.test_openclaw -v
"""

import json
import os
import re
import unittest

from tests.adapters._helpers import assert_no_em_dash, assert_no_emoji

# Resolve the openclaw-plugin root from this file's location:
#   tests/openclaw/test_openclaw.py -> openclaw-plugin is two parents up
#   then into openclaw-plugin/.
_PLUGIN_ROOT = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
)
OPENCLAW_DIR = os.path.join(_PLUGIN_ROOT, "openclaw-plugin")

# Expected tool names - must match contracts.tools in the manifest and
# the tool() declarations in src/index.ts.
EXPECTED_TOOLS = [
    "adjacent_doctor",
    "adjacent_brief",
    "adjacent_snapshot",
    "adjacent_chart",
    "adjacent_movers",
    "adjacent_capabilities",
    "adjacent_mcp_query",
    "adjacent_topic_brief",
    "adjacent_news_latest",
    "adjacent_news_correlation",
    "adjacent_correlation_regime",
    "adjacent_portfolio_snapshot",
    "adjacent_tracking",
    "adjacent_tracking_table",
    "adjacent_chart_csv",
    "adjacent_candles_chart",
    "adjacent_similar_hedges",
    "adjacent_snapshot_health",
    "adjacent_datawrapper_index",
    "adjacent_http_get",
    "adjacent_rebalance_plan",
]

# The shared Python core bundled into the tarball so a clean install needs
# no repo checkout.
BUNDLED_DIRS = ["scripts", "data", "skills"]

# Keywords that would indicate a trading or shell-execution capability -
# forbidden in a read-only plugin.
FORBIDDEN_KEYWORDS = ["execute order", "shell exec", "subprocess", "spawn"]


def _read(rel_path: str) -> str:
    full = os.path.join(OPENCLAW_DIR, rel_path)
    with open(full, "r", encoding="utf-8") as fh:
        return fh.read()


def _file_exists(rel_path: str) -> bool:
    return os.path.isfile(os.path.join(OPENCLAW_DIR, rel_path))


class TestManifest(unittest.TestCase):
    """Validate openclaw.plugin.json structure and required fields."""

    def test_manifest_exists(self):
        self.assertTrue(
            _file_exists("openclaw.plugin.json"),
            "openclaw.plugin.json is missing from the plugin root",
        )

    def test_manifest_is_valid_json(self):
        data = json.loads(_read("openclaw.plugin.json"))
        self.assertIsInstance(data, dict)

    def test_manifest_has_id(self):
        data = json.loads(_read("openclaw.plugin.json"))
        self.assertEqual(data.get("id"), "adjacent-markets")

    def test_manifest_has_name_and_description(self):
        data = json.loads(_read("openclaw.plugin.json"))
        self.assertTrue(data.get("name"), "manifest missing name")
        self.assertTrue(data.get("description"), "manifest missing description")

    def test_manifest_has_config_schema(self):
        data = json.loads(_read("openclaw.plugin.json"))
        schema = data.get("configSchema")
        self.assertIsInstance(schema, dict)
        self.assertEqual(schema.get("type"), "object")
        # The manifest is generated by `openclaw plugins build`; it exposes
        # apiKey and tier and omits additionalProperties by design.
        self.assertIn("apiKey", schema.get("properties", {}))
        self.assertIn("tier", schema.get("properties", {}))

    def test_manifest_has_contracts_tools(self):
        data = json.loads(_read("openclaw.plugin.json"))
        tools = data.get("contracts", {}).get("tools", [])
        self.assertIsInstance(tools, list)
        self.assertEqual(
            sorted(tools),
            sorted(EXPECTED_TOOLS),
            "contracts.tools does not match expected tool names",
        )

    def test_manifest_has_activation(self):
        data = json.loads(_read("openclaw.plugin.json"))
        activation = data.get("activation", {})
        self.assertIsInstance(activation, dict)
        self.assertIn("onStartup", activation)

    def test_manifest_has_mcp_servers(self):
        data = json.loads(_read("openclaw.plugin.json"))
        servers = data.get("mcpServers", {})
        self.assertIn("adjacent-markets", servers)
        self.assertIn("adjacent-markets-dev", servers)

    def test_manifest_no_em_dash_or_emoji(self):
        text = _read("openclaw.plugin.json")
        self.assertEqual(assert_no_em_dash(text), [], "manifest has em-dash")
        self.assertEqual(assert_no_emoji(text), [], "manifest has emoji")

    def test_manifest_description_mentions_readonly(self):
        text = _read("openclaw.plugin.json").lower()
        self.assertIn("read-only", text)


class TestPackageJson(unittest.TestCase):
    """Validate package.json openclaw metadata and dependencies."""

    def test_package_json_exists(self):
        self.assertTrue(_file_exists("package.json"))

    def test_package_json_is_valid_json(self):
        data = json.loads(_read("package.json"))
        self.assertIsInstance(data, dict)

    def test_package_type_is_module(self):
        data = json.loads(_read("package.json"))
        self.assertEqual(data.get("type"), "module")

    def test_package_has_openclaw_extensions(self):
        data = json.loads(_read("package.json"))
        oc = data.get("openclaw", {})
        self.assertIsInstance(oc, dict)
        extensions = oc.get("extensions", [])
        self.assertIsInstance(extensions, list)
        self.assertIn("./src/index.ts", extensions)

    def test_package_has_runtime_extensions(self):
        data = json.loads(_read("package.json"))
        oc = data.get("openclaw", {})
        runtime = oc.get("runtimeExtensions", [])
        self.assertIsInstance(runtime, list)
        self.assertIn("./dist/index.js", runtime)

    def test_package_has_typebox_dependency(self):
        data = json.loads(_read("package.json"))
        deps = data.get("dependencies", {})
        self.assertIn("typebox", deps, "typebox must be in dependencies, not devDependencies")

    def test_package_has_openclaw_peer_dependency(self):
        data = json.loads(_read("package.json"))
        peers = data.get("peerDependencies", {})
        self.assertIn("openclaw", peers)

    def test_package_has_build_scripts(self):
        data = json.loads(_read("package.json"))
        scripts = data.get("scripts", {})
        self.assertIn("build", scripts)
        self.assertIn("plugin:build", scripts)
        self.assertIn("plugin:validate", scripts)

    def test_package_files_includes_manifest_and_dist(self):
        data = json.loads(_read("package.json"))
        files = data.get("files", [])
        self.assertIn("dist", files)
        self.assertIn("openclaw.plugin.json", files)
        self.assertIn("README.md", files)

    def test_package_no_em_dash_or_emoji(self):
        text = _read("package.json")
        self.assertEqual(assert_no_em_dash(text), [], "package.json has em-dash")
        self.assertEqual(assert_no_emoji(text), [], "package.json has emoji")


class TestEntrypoint(unittest.TestCase):
    """Validate src/index.ts uses defineToolPlugin and declares the expected tools."""

    def test_entrypoint_exists(self):
        self.assertTrue(_file_exists("src/index.ts"))

    def test_uses_define_tool_plugin(self):
        text = _read("src/index.ts")
        self.assertIn(
            "defineToolPlugin",
            text,
            "entrypoint must use defineToolPlugin from openclaw/plugin-sdk/tool-plugin",
        )
        self.assertIn(
            "openclaw/plugin-sdk/tool-plugin",
            text,
            "entrypoint must import from openclaw/plugin-sdk/tool-plugin",
        )

    def test_uses_typebox(self):
        text = _read("src/index.ts")
        self.assertIn('from "typebox"', text)
        self.assertIn("Type.Object", text)

    def test_declares_expected_tools(self):
        text = _read("src/index.ts")
        for tool_name in EXPECTED_TOOLS:
            with self.subTest(tool=tool_name):
                self.assertIn(
                    'name: "%s"' % tool_name,
                    text,
                    "entrypoint does not declare tool %s" % tool_name,
                )

    def test_plugin_id_matches_manifest(self):
        text = _read("src/index.ts")
        self.assertIn('id: "adjacent-markets"', text)

    def test_no_order_placement(self):
        text = _read("src/index.ts").lower()
        for bad in FORBIDDEN_KEYWORDS:
            with self.subTest(keyword=bad):
                self.assertNotIn(
                    bad,
                    text,
                    "entrypoint contains forbidden keyword: %s" % bad,
                )

    def test_mid_quote_convention_present(self):
        text = _read("src/index.ts").lower()
        self.assertIn("mid", text, "entrypoint must reference mid-quote convention")

    def test_no_pp_unit(self):
        """The entrypoint must not use 'pp' as a unit (only %)."""
        text = _read("src/index.ts")
        # 'pp' as a standalone unit token is banned. We check for common
        # patterns but allow 'pp' inside identifiers like 'app' or 'happens'.
        # The banned usage is as a unit: e.g. "in pp" or "unit: pp".
        for pattern in (r'unit["\']?\s*[:=]\s*["\']pp', r'in\s+pp\b', r'\bpp\b\s*$'):
            matches = re.findall(pattern, text, re.MULTILINE)
            self.assertEqual(
                matches,
                [],
                "entrypoint uses banned 'pp' unit: %s" % matches,
            )

    def test_no_em_dash_or_emoji(self):
        text = _read("src/index.ts")
        self.assertEqual(assert_no_em_dash(text), [], "src/index.ts has em-dash")
        self.assertEqual(assert_no_emoji(text), [], "src/index.ts has emoji")

    def test_default_export_present(self):
        text = _read("src/index.ts")
        self.assertIn("export default", text)

    def test_no_shell_or_subprocess_import(self):
        text = _read("src/index.ts")
        for bad in ("child_process", "execSync", "spawn", "exec("):
            with self.subTest(token=bad):
                self.assertNotIn(
                    bad,
                    text,
                    "entrypoint must not import or use shell execution: %s" % bad,
                )


class TestTsconfig(unittest.TestCase):
    """Validate tsconfig.json produces ESM output to dist/."""

    def test_tsconfig_exists(self):
        self.assertTrue(_file_exists("tsconfig.json"))

    def test_tsconfig_is_valid_json(self):
        data = json.loads(_read("tsconfig.json"))
        self.assertIsInstance(data, dict)

    def test_tsconfig_output_to_dist(self):
        data = json.loads(_read("tsconfig.json"))
        self.assertEqual(data["compilerOptions"]["outDir"], "./dist")

    def test_tsconfig_module_is_nodenext(self):
        data = json.loads(_read("tsconfig.json"))
        self.assertEqual(data["compilerOptions"]["module"], "NodeNext")

    def test_tsconfig_strict(self):
        data = json.loads(_read("tsconfig.json"))
        self.assertTrue(data["compilerOptions"]["strict"])

    def test_tsconfig_root_dir_is_src(self):
        data = json.loads(_read("tsconfig.json"))
        self.assertEqual(data["compilerOptions"]["rootDir"], "./src")

    def test_tsconfig_includes_src(self):
        data = json.loads(_read("tsconfig.json"))
        self.assertIn("src/**/*.ts", data.get("include", []))


class TestReadme(unittest.TestCase):
    """Validate the concise OpenClaw setup guide."""

    def test_readme_exists(self):
        self.assertTrue(_file_exists("README.md"))

    def test_readme_documents_install(self):
        text = _read("README.md")
        self.assertIn("openclaw plugins install", text)
        self.assertIn("openclaw plugins inspect", text)

    def test_readme_documents_build(self):
        text = _read("README.md")
        self.assertIn("npm run build", text)
        self.assertIn("plugin:validate", text)

    def test_readme_documents_test_command(self):
        text = _read("README.md")
        self.assertIn("python3 -m unittest", text)
        self.assertIn("test_openclaw", text)

    def test_readme_mentions_readonly_safety(self):
        text = _read("README.md").lower()
        self.assertIn("read-only", text)
        self.assertIn("never places an order", text)

    def test_readme_mentions_mid_quote(self):
        text = _read("README.md").lower()
        self.assertIn("mid", text)

    def test_readme_no_em_dash_or_emoji(self):
        text = _read("README.md")
        self.assertEqual(assert_no_em_dash(text), [], "README has em-dash")
        self.assertEqual(assert_no_emoji(text), [], "README has emoji")


class TestCrossFileConsistency(unittest.TestCase):
    """Validate that the manifest, package, and entrypoint agree."""

    def test_tool_names_match_manifest_and_entrypoint(self):
        manifest = json.loads(_read("openclaw.plugin.json"))
        manifest_tools = sorted(manifest["contracts"]["tools"])
        entry_text = _read("src/index.ts")
        for tool_name in manifest_tools:
            self.assertIn(
                'name: "%s"' % tool_name,
                entry_text,
                "tool %s in manifest but not in entrypoint" % tool_name,
            )
        self.assertEqual(manifest_tools, sorted(EXPECTED_TOOLS))

    def test_plugin_id_matches_manifest_and_entrypoint(self):
        manifest = json.loads(_read("openclaw.plugin.json"))
        entry_text = _read("src/index.ts")
        self.assertEqual(manifest["id"], "adjacent-markets")
        self.assertIn('id: "adjacent-markets"', entry_text)

    def test_entry_extension_in_package_matches_entrypoint_path(self):
        pkg = json.loads(_read("package.json"))
        oc = pkg["openclaw"]
        self.assertIn("./src/index.ts", oc["extensions"])
        self.assertIn("./dist/index.js", oc["runtimeExtensions"])
        self.assertTrue(_file_exists("src/index.ts"))

    def test_mcp_server_names_match_manifest(self):
        manifest = json.loads(_read("openclaw.plugin.json"))
        servers = manifest.get("mcpServers", {})
        self.assertIn("adjacent-markets", servers)
        self.assertIn("adjacent-markets-dev", servers)
        for name, cfg in servers.items():
            with self.subTest(server=name):
                self.assertEqual(cfg.get("transport"), "stdio")
                self.assertIn("command", cfg)
                self.assertIn("args", cfg)


class TestRuntimeSafety(unittest.TestCase):
    """The runtime executes the shared core, so pin how it is allowed to do it.

    Execution moved out of src/index.ts into src/runtime.ts. The safety
    property is no longer "cannot execute" but "executes only allowlisted
    scripts, with an argv array and the shell disabled".
    """

    def test_runtime_exists(self):
        self.assertTrue(_file_exists("src/runtime.ts"))

    def test_spawn_disables_the_shell(self):
        text = _read("src/runtime.ts")
        self.assertIn("shell: false", text, "runtime must spawn with the shell disabled")

    def test_no_string_command_execution(self):
        text = _read("src/runtime.ts")
        for bad in ("execSync", "exec(", "spawnSync"):
            with self.subTest(token=bad):
                self.assertNotIn(bad, text, "runtime must not run a command string: %s" % bad)

    def test_declares_a_script_allowlist(self):
        text = _read("src/runtime.ts")
        self.assertIn("ALLOWED_SCRIPTS", text)
        self.assertIn("is not allowlisted", text)

    def test_rebalance_is_dry_run_only(self):
        """rebalance-index.py is allowlisted for dry-run plans but must
        always be called with --dry-run. No order is ever submitted."""
        runtime = _read("src/runtime.ts")
        self.assertIn("rebalance-index.py", runtime, "rebalance-index.py must be in the allowlist for dry-run plans")
        entry = _read("src/index.ts")
        # The rebalance plan tool must hardcode --dry-run.
        self.assertIn('"--dry-run"', entry, "rebalance plan tool must force --dry-run")

    def test_allowlisted_scripts_exist_in_the_repo(self):
        text = _read("src/runtime.ts")
        listed = re.findall(r'"([a-z0-9-]+\.py)"', text)
        self.assertTrue(listed, "no scripts found in the allowlist")
        for name in listed:
            with self.subTest(script=name):
                self.assertTrue(
                    os.path.isfile(os.path.join(_PLUGIN_ROOT, "scripts", name)),
                    "allowlisted script does not exist: %s" % name,
                )

    def test_prefers_env_overrides_then_bundle(self):
        text = _read("src/runtime.ts")
        self.assertIn("ADJACENT_PLUGIN_SCRIPTS", text)
        self.assertIn("ADJACENT_PLUGIN_ROOT", text)
        self.assertIn("runtime", text)

    def test_state_dir_is_outside_the_package(self):
        """Artifacts must not be written into node_modules."""
        text = _read("src/runtime.ts")
        self.assertIn("ADJACENT_STATE_DIR", text)
        self.assertIn("process.cwd()", text)

    def test_no_em_dash_or_emoji(self):
        text = _read("src/runtime.ts")
        self.assertEqual(assert_no_em_dash(text), [], "src/runtime.ts has em-dash")
        self.assertEqual(assert_no_emoji(text), [], "src/runtime.ts has emoji")


class TestBundling(unittest.TestCase):
    """A clean install must carry the shared core, with no repo checkout."""

    def test_bundler_exists(self):
        self.assertTrue(_file_exists("scripts/bundle-runtime.mjs"))

    def test_bundler_copies_core_and_skills(self):
        text = _read("scripts/bundle-runtime.mjs")
        for name in BUNDLED_DIRS:
            with self.subTest(directory=name):
                self.assertIn('"%s"' % name, text)

    def test_bundler_excludes_the_repo_validator(self):
        """The package validator is repo tooling, not runtime."""
        text = _read("scripts/bundle-runtime.mjs")
        self.assertIn("validate-plugin-packages.py", text)

    def test_package_files_ships_the_runtime(self):
        pkg = json.loads(_read("package.json"))
        self.assertIn("runtime", pkg["files"], "files must ship the bundled runtime")
        self.assertIn("dist", pkg["files"])

    def test_prepack_builds_and_bundles(self):
        pkg = json.loads(_read("package.json"))
        prepack = pkg["scripts"].get("prepack", "")
        self.assertIn("build", prepack, "prepack must compile dist")
        self.assertIn("bundle", prepack, "prepack must bundle the shared core")

    def test_bundled_layout_matches_the_path_helper(self):
        """runtime/scripts + runtime/data is what _paths.py expects."""
        text = _read("scripts/bundle-runtime.mjs")
        self.assertIn('join(RUNTIME_DIR, "scripts")', text)
        self.assertIn('join(RUNTIME_DIR, "data")', text)


if __name__ == "__main__":
    unittest.main()
